### ISSUE TITLE
Сrash during decoding

### ISSUE THREAD

**Issue by nvkzNemo** [autoboosh/jsxbin-to-jsx-converter#1]
File: https://www.dropbox.com/s/3j7fklu5k8wmkbf/OnSelectLayer.jsxbin?dl=0

![](https://api.monosnap.com/rpc/file/download?id=oHzOt4Y9QGw7wv5b2NVZNV2WLNXFrM)

**Comment by autoboosh** [comment]
What application did you use to create this file? ExtendScript Toolkit usually wraps jsxbin encoded files after 80 characters with a newline 0xA. But yours seems to include an additional backslash.

It works after removing the backslashes. Here's the decoded file: http://pastebin.com/36qNfMjt.

I'll amend the decoder to strip away all characters not belonging to the "decoding alphabet". Thank you for raising this issue :)

**Comment by autoboosh** [comment]
Looks like this is copied code straight out of a string? "Line continuation" or something like that: http://stackoverflow.com/a/805113. Commit f5d19e0e9e611d9a1fa64f55c89eaeff1a62a0ec fixes this.

The new version will be up by the end of the week :)
