### ISSUE TITLE
Version 1.6 err Input string was not in a correct format

### ISSUE THREAD

**Issue by exclusives** [autoboosh/jsxbin-to-jsx-converter#6]
R:\Ryuk\ae>jsxbin_to_jsx.exe file.jsxbin file.jsx > err.txt
[err.txt](https://github.com/autoboosh/jsxbin-to-jsx-converter/files/89742/err.txt)

**Comment by autoboosh** [comment]
What does the JSXBIN file look like?

**Comment by exclusives** [comment]
Any files
for examples:
jsxbin-to-jsx-converter-master.zip\testfiles\v1.0\xml.jsxbin
jsxbin-to-jsx-converter-master.zip\testfiles\v1.0\variables.jsxbin

jsxbin-to-jsx-converter-master.zip\testfiles\v2.0\xml.jsxbin
jsxbin-to-jsx-converter-master.zip\testfiles\v2.0\variables.jsxbin

my os is win8

**Comment by autoboosh** [comment]
Can you copy paste the beginning of one of those jsxbin files here? Just the first line should be enough. Thanks!

**Comment by exclusives** [comment]
@JSXBIN@ES@1.0@MAbyBn0ABJAnASzGjSjFjTjVjMjUByBCzChdhdCXzJiAjDjBjUjFjHjPjSjZDXzEj
CjPjPjLEjzMjCjPjPjLjTjUjPjSjFiYiNiMFnneIiDiIiJiMiEiSiFiOnftABB40BiAABAzAGByB

from xml.jsxbin
There are files from the archive that I had downloaded here

**Comment by autoboosh** [comment]
Might be an issue with the double parsing being culture sensitive. Should be fixed in 0091b7e6312ecbf444396d573e907db3447c466c. New release is up at   [Version 1.7](https://github.com/autoboosh/jsxbin-to-jsx-converter/releases/tag/1.7) which should fix the issue.

Let me know how it goes.

**Comment by exclusives** [comment]
Thank you very much!
Program Worked!
